# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 08:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='API',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('bash_script', models.TextField()),
                ('outputs_dir', models.CharField(max_length=200)),
                ('input_params', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_params', jsonfield.fields.JSONField()),
                ('api_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.API')),
            ],
        ),
    ]
