# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 11:25
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='request',
            name='preferred_run_date',
            field=models.DateField(default=datetime.date(2017, 11, 27)),
        ),
        migrations.AddField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('processing', 'Processing'), ('finished', 'Finished')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='api',
            name='input_params',
            field=models.CharField(max_length=200, validators=[main.validators.validate_comma_separated]),
        ),
    ]
