# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 11:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20171126_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='preferred_run_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
