# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 13:24
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20171129_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='input_params',
            field=jsonfield.fields.JSONField(blank=True),
        ),
    ]
